### ISSUE TITLE
Plugin not working - Mac - Safari

### ISSUE THREAD

**Issue by neozzz** [jaclyntan/figma-color-overlay#2]
It seems to be easy to use, however I was unable change colour to any of Images I downloaded from the google (PNG). with Alpha or not. Using Mac - Safari, refreshing or reopening pages didn't make any changes. But it working on Chrome on the same computer.

**Comment by jaclyntan** [comment]
Hi there,
Sorry for the late reply I've only just recently gotten around to testing this. The plugin doesn't seem to work on Safari because of memory issues. I don't think there is currently a fix available for this as I cannot debug the plugin on Safari, so please use Google Chrome or the Figma app if you would like to continue using this plugin. Thanks ♡
